spring:
  application.name: wiam
  threads:
    virtual:
      enabled: true

server:
  port: 8081

  logging:
    level:
      it.**.advice: { $LOG_LEVEL:INFO }
    pattern.level: '%5p [traceId=%X{tracingId}]'

  #aggignere stringa di connessione a mongo db locale
  #comando per startare db da terminale : brew services start mongodb-community@7.0
  #comando per chiudere db da terminale: brew services stop mongodb-community@7.0
  data:
    mongodb:
      uri: mongodb://localhost:27017/tsm-ur-card-list
